name: flutter_auth
description: A Flutter Package to Support Email and Phone Authentication.
version: 0.0.2
homepage: https://github.com/bishalimtiaz/flutter_auth.git
#repository: https://github.com/bishalimtiaz/flutter_auth.git

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.2
  fluttertoast: ^8.0.9
  country_pickers: ^2.0.0
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - images/
